config/routes.rb
Rails.application.routes.draw do
  root to: 'fruits#index'

  resources :fruits
  resources :messages, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fruit.rb
class Fruit < ApplicationRecord
  include RankedModel
  ranks :row_order

  has_one_attached :image
  has_one_attached :image2, service: :server_side_encrypted_s3
  has_one_attached :image3, service: :client_side_encrypted_s3
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  def preview
    preview_data = ::ActiveStorage::Attachments::Preview.new(attachment).call
    send_data(
      preview_data,
      filename: attachment.image3.filename.to_s,
      type: 'image/jpeg'
    )
  end

  private

  def attachment
    @attachment ||= Fruit.find params["fruit_id"]
  end
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  before_action :set_fruit, only: [:show, :edit, :update, :destroy]

  # GET /fruits
  # GET /fruits.json
  def index
    @fruits = Fruit.rank(:row_order)
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
  end

  # GET /fruits/new
  def new
    @fruit = Fruit.new
  end

  # GET /fruits/1/edit
  def edit
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(fruit_params)

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: 'Fruit was successfully created.' }
        format.json { render :show, status: :created, location: @fruit }
      else
        format.html { render :new }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fruits/1
  # PATCH/PUT /fruits/1.json
  def update
    respond_to do |format|
      if @fruit.update(fruit_params)
        format.html { redirect_to @fruit, notice: 'Fruit was successfully updated.' }
        format.json { render :show, status: :ok, location: @fruit }
      else
        format.html { render :edit }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit.destroy
    respond_to do |format|
      format.html { redirect_to fruits_url, notice: 'Fruit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # this action will be called via ajax
  def sort
    fruit = Fruit.find(params[:fruit_id])
    fruit.update(fruit_params)
    render nothing: true
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fruit
      @fruit = Fruit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fruit_params
      params.require(:fruit).permit(:name, :row_order_position, :image, :image2, :image3)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruit_helper.rb
module FruitHelper
end

app/helpers/message_helper.rb
module MessageHelper
end

app/views/fruits/_form.html.slim
= form_for @fruit do |f|
  - if @fruit.errors.any?
    #error_explanation
      h2 = "#{pluralize(@fruit.errors.count, "error")} prohibited this fruit from being saved:"
      ul
        - @fruit.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
    br
    = f.label :image
    = f.file_field :image, direct_upload: true
    br
    = f.label :image2
    = f.file_field :image2, direct_upload: true
    br
    = f.label :image3
    = f.file_field :image3, direct_upload: true
  .actions = f.submit 'Save'

app/views/fruits/edit.html.slim
h1 Editing fruit

== render 'form'

= link_to 'Show', @fruit
'|
= link_to 'Back', fruits_path

app/views/fruits/index.html.slim
h1 Listing fruits

table.table.table-bordered.table-sortable
  thead
    tr
      th Name
      th image
      th
      th
      th

  tbody
    - @fruits.each do |fruit|
      tr.item(data = { model_name: fruit.class.name.underscore, update_url: fruits_path(fruit) })
        td = fruit.name
        td = fruit.image.attached? ? image_tag(fruit.image.variant(resize_to_fill: [100, nil])) : nil
        td = link_to 'Show', fruit
        td = link_to 'Edit', edit_fruit_path(fruit)
        td = link_to 'Destroy', fruit, data: { "turbo-method": :delete , "turbo-confirm": "Are you sure?"}

br

= link_to 'New Fruit', new_fruit_path

app/views/fruits/new.html.slim
h1 New fruit

== render 'form'

= link_to 'Back', fruits_path

app/views/fruits/show.html.slim
p#notice = notice

p
  strong Name:
  = @fruit.name

p
  strong Image:
  - if @fruit.image.attached?
    = image_tag(@fruit.image.variant(resize_to_fill: [860, 573]))

= link_to 'Edit', edit_fruit_path(@fruit)
'|
= link_to 'Back', fruits_path

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 4.6
nav.navbar.navbar-inverse.navbar-fixed-top.navbar-dark.bg-dark
  .container
    .navbar-header
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'ChatMessage', messages_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Sortable Table Sandbox'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Sortable Table Sandbox'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application', "data-turbo-track": "reload", defer: true
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      .container
        .row
          .col-md-12
            == render 'layouts/messages'
            == yield

app/views/messages/_message.slim
.message__speech-bubble
  p = message.content

app/views/messages/_messages.slim
.message__speech-bubble
  p = message.content

app/views/messages/index.html.slim
h1 Chat Room

#messages data-controller="chat" data-chat-target="messages"
  = render @messages
= form_with model: @message, data: { controller: "chat", action: "submit->chat#submit" } do |form|
  = form.text_area :content, data: { "chat-target": "input" }, class: "message__content-area"
  = form.submit "Send", class: "message__send-button"